CMPUT301W24T02/Thesixproject

- .idea/deploymentTargetDropDown.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/thesix/AttendeeListCreateActivity.java
- app/src/main/java/com/example/thesix/AttendeeListDB.java
- app/src/main/java/com/example/thesix/MainActivity.java
- app/src/main/java/com/example/thesix/OrganizerUseNewQRActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/attendee_list_screen.xml
- app/src/main/res/layout/organizer_use_new_qr_screen.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Known Issues- "Welcome Organizer" Text disappears when running, maybe has to do with relative layout setup.
> Welcome Organizer Page and buttons, Guest List Navigation 

- app/src/main/java/com/example/thesix/Attendee.java
- app/src/main/java/com/example/thesix/AttendeeDB.java
- app/src/main/java/com/example/thesix/AttendeeListAdapter.java
- app/src/main/java/com/example/thesix/AttendeeListConnector.java
- app/src/main/java/com/example/thesix/AttendeeListCreateActivity.java
- app/src/main/java/com/example/thesix/AttendeeListDB.java
- app/src/main/java/com/example/thesix/MainActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/attendee_list_content.xml
- app/src/main/res/layout/attendee_list_screen.xml
- app/src/main/res/layout/organizer_create_screen.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- List view for attendee added
- Attendee classes added to be connected to Database
> Organizer Story Point Work- Attendee View

- app/src/main/java/com/example/thesix/AttendeeDB.java
- app/src/main/java/com/example/thesix/AttendeeMainActivity.java
- app/src/main/java/com/example/thesix/MainActivity.java
Merge main branch to Jingru's branch
> Merge main branch to Jingru's branch

- app/src/main/res/layout/attendee_main_activity.xml
- app/src/main/res/values/strings.xml
Merge Jingru's branch to main: Change the layout of attendee main activity
> Change the layout of attendee main activity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/thesix/AttendeeMainActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/res/layout/attendee_profile_screen.xml
Merge Jingru's branch to main: Update attendee view profile button: switch activity
> Update attendee view profile button: switch activity

- app/src/main/java/com/example/thesix/Attendee.java
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/res/layout/attendee_profile_screen.xml
Merge Jingru's branch to main: Update Attendee class and attendee profile layout
> Update Attendee class and attendee profile layout

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
- app/src/main/res/drawable/button_background.xml
- app/src/main/res/layout/attendee_profile_screen.xml
- app/src/main/res/layout/attendee_profile_update.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
merge Jingru's branch to main: add attendee profile information update page
> add attendee profile information update page

- app/src/main/java/com/example/thesix/Attendee.java
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
- app/src/main/res/layout/attendee_profile_update.xml
accomplish attendee information update in the app( not in the database) and fixed some  existing back button bug
> accomplish attendee information update in the app

- app/src/main/java/com/example/thesix/AttendeeDB.java
- app/src/main/java/com/example/thesix/AttendeeListActivity.java
Deleting log comments, and extra lines
> Attendee File Cleanup

- app/src/main/java/com/example/thesix/AttendeeMainActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Merge Jingru's  branch to main: accomplish attendee information update to database
> accomplish attendee information update to database

- app/src/main/java/com/example/thesix/AdminImagesActivity.java
- app/src/main/java/com/example/thesix/AdminProfileActivity.java
- app/src/main/java/com/example/thesix/MainActivity.java
> Admin Images Activity

- app/src/main/java/com/example/thesix/AttendeeDB.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Merge Jingru's branch to main: Edit AttendeeDB file and AttendeeProfileActivity
> Edit AttendeeDB file and AttendeeProfileActivity

- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Merge Jingru's branch to main: Fixed existing bug of Attendee Profile
> Fixed existing bug of Attendee Profile

- app/src/main/java/com/example/thesix/AttendeeMainActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Merge Jingru's branch to main: Update Attendee Profile Image Upload
> Update Attendee Profile Image Upload

- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Merge Jingru's branch to Main: Fixed database not connected to Attendee Profile Update
> Fixed database not connected to Attendee Profile Update

- app/src/main/java/com/example/thesix/AttendeeDB.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Merge Jingru's branch to main: connect attendee profile image to database
> Connect attendee profile image to database

- app/src/main/java/com/example/thesix/AttendeeDB.java
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
- app/src/main/res/layout/attendee_profile_update.xml
Merge Jingru's branch to main: Accomplish remove attendee profile picture button
> Accomplish remove attendee profile picture button

- app/src/main/java/com/example/thesix/AdminImagesActivity.java
- app/src/main/java/com/example/thesix/AdminProfileActivity.java
- app/src/main/java/com/example/thesix/CustomImageAdapter.java
- app/src/main/res/layout/admin_images_screen.xml
- app/src/main/res/layout/image_list_content.xml
- Need to update where to pull from in firestore to get all images.
> Images Show in list

- app/src/main/java/com/example/thesix/AdminImagesActivity.java
- app/src/main/java/com/example/thesix/CustomImageAdapter.java
- app/src/main/java/com/example/thesix/MainActivity.java
- app/src/main/res/layout/admin_images_screen.xml
- app/src/main/res/layout/admin_profile_screen.xml
- app/src/main/res/layout/event_list.xml
- app/src/main/res/layout/image_list_content.xml
-Pull event poster image for images- need to pull profile images as well
-formatting on list views-dynamic
-Javadocs
> Admin Menu Updates

- app/src/main/java/com/example/thesix/AdminProfileActivity.java
- app/src/main/java/com/example/thesix/AdminProfileListAdapter.java
Note: All Profiles must contain images, if no image a default must be generated for this not to crash.
> Profile List Displays Image of Guest

- app/src/main/java/com/example/thesix/AdminImagesActivity.java
All Images Grabbed and displayed
Variables : profile_image and eventimageData must never be empty
> Image Listing Done

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/thesix/MainActivity.java
- app/src/main/java/com/example/thesix/PushNotificationService.java
change gradle and manifest so app can use firebase messaging service
> change gradle and manifest so app can use firebase messaging service

- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Change all EditText field in AttendeeProfile can not be nul
> Change all EditText field in AttendeeProfile can not be null

- .idea/androidTestResultsUserPreferences.xml
- .idea/deploymentTargetDropDown.xml
- app/src/androidTest/java/com/example/thesix/AttendeeProfileActivityTest.java
- app/src/androidTest/java/com/example/thesix/AttendeeProfileUpdateTest.java
Add some UI Test template for Attende
> Add some UI Test template for Attendee

- .idea/androidTestResultsUserPreferences.xml
- .idea/deploymentTargetDropDown.xml
- app/src/androidTest/java/com/example/thesix/AttendeeMainActivityTest.java
- app/src/androidTest/java/com/example/thesix/AttendeeProfileActivityTest.java
- app/src/androidTest/java/com/example/thesix/AttendeeProfileUpdateTest.java
> Update Attendee UI Test

- .idea/deploymentTargetDropDown.xml
- app/src/androidTest/java/com/example/thesix/AdminActivityTest.java
Add some AdminActivity UI Test
> Add some AdminActivity UI Test

- app/src/main/java/com/example/thesix/AdminEventsActivity.java
- app/src/main/java/com/example/thesix/MainActivity.java
- app/src/main/res/layout/profile_list_content.xml
> Profile Image Listing View updates

- app/src/main/java/com/example/thesix/AdminEventsActivity.java
- app/src/main/java/com/example/thesix/AdminImagesActivity.java
- app/src/main/java/com/example/thesix/AdminProfileActivity.java
- app/src/main/java/com/example/thesix/MainActivity.java
- app/src/main/res/layout/admin_images_screen.xml
Images converted to 2 list view instead
images remove from list,
ToDo: Removal from firestore methods
> Image List Removal

- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Add word limit 25 for Attendee Profile info
> Add word limit 25 for Attendee Profile info

- .idea/misc.xml
- app/src/main/java/com/example/thesix/AttendeeMainActivity.java
- app/src/main/java/com/example/thesix/EventDetailsAdapter.java
- app/src/main/java/com/example/thesix/MainActivity.java
- app/src/main/java/com/example/thesix/OrganizerMainActivity.java
- app/src/main/java/com/example/thesix/QrCodeDB.java
> Merge main branch to jingru2

- app/src/androidTest/java/com/example/thesix/AttendeeMainActivityTest.java
update AttendeeMainActivity UI test
> update AttendeeMainActivity UI test

- app/src/main/java/com/example/thesix/AttendeeDB.java
- app/src/main/java/com/example/thesix/AttendeeProfileActivity.java
- app/src/main/java/com/example/thesix/AttendeeProfileUpdate.java
Fixed profile picture upload bug
> Fixed profile picture upload bug

- app/src/main/java/com/example/thesix/AttendeeMainActivity.java
- app/src/main/java/com/example/thesix/AttendeePromoActivity.java
> Merge main to Jingru2
